#!/usr/bin/env php
# app/console
<?php
require __DIR__.'/vendor/autoload.php';
use PV\Inova\Command\DeployCommand;
use PV\Inova\Command\DeployConfigCommand;
use Symfony\Component\Console\Application;

$application = new Application();
$application->add(new DeployCommand);
$application->add(new DeployConfigCommand);
$application->run();